#change configfile to point to experiment_config.yaml for this experiment
#change mkdir, --output and --error to point to log folder for this experiment
#change mail-user, mail-type to point to your email
#can change default resources or set-resources as needed


snakefile: Snakefile.py
use-conda: True
conda-frontend: conda
rerun-incomplete: True
restart-times: 1
jobs: 100
latency-wait: 50
keep-going: True
configfile: ./experiment_info.yaml
conda-prefix: /nfs/tamilab001/c3ddb-scratch-mit_lieberman/tools/conda_snakemake
cluster-status: ./scripts/slurm_status.py
reason: True
#dryrun: True
#rerun-triggers: mtime
#unlock: True

cluster:
  mkdir -p ./logs/ &&
  sbatch
    --partition={resources.partition}
    --ntasks={resources.ntasks}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name="SM.{rule}"
    --output="./logs/%j_{rule}.err.txt"
    --error="./logs/%j_{rule}.err.txt"
    --exclude=""
    --mail-user="YOUR_EMAIL_HERE"
    --mail-type="FAIL"

#note that resource names should use underscore _ instead of dash -

default-resources:
   - partition="YOUR_PARTITION_HERE"
   - time="1:00:00"
   - ntasks=1
   - cpus_per_task=1
   - mem=8000

set-resources:
   # cutadapt
   - cutadapt:ntasks=1
   - cutadapt:cpus_per_task=1
   - cutadapt:time="04:00:00"
   # sickle
   - sickle:ntasks=1
   - sickle:cpus_per_task=1
   - sickle:time="04:00:00"
   # bowtie2
   - bowtie2:mem=64000
   - bowtie2:cpus_per_task=8
   - bowtie2:time="02:00:00"
   # sam2bam
   - sam2bam:mem=64000
   - sam2bam:cpus_per_task=1
   - sam2bam:time="12:00:00"
   # mpileup2vcf
   - mpileup2vcf:mem=60000
   - mpileup2vcf:cpus_per_task=1
   - mpileup2vcf:time="12:00:00"
   # pileup2diversity_matrix
   - pileup2diversity_matrix:mem=60000
   - pileup2diversity_matrix:cpus_per_task=1
   - pileup2diversity_matrix:time="12:00:00"
   # variants2positions
   - variants2positions:mem=60000
   - variants2positions:mem_per_cpu=60000
   - variants2positions:cpus_per_task=1
   - variants2positions:time="02:00:00"
   # combine_positions
   - combine_positions:mem=60000
   - combine_positions:mem_per_cpu=60000
   - combine_positions:cpus_per_task=1
   - combine_positions:time="02:00:00"
   # classify
   - classify:mem=16G
   - classify:cpus_per_task=1
   - classify:time="12:00:00"
   # plot
   - plot:mem=10G
   - plot:cpus_per_task=1
   - plot:time="1:00:00"